version: '2'
services:
    pocjhipster-app:
        image: pocjhipster
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://pocjhipster-postgresql:5432/pocjhipster
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pocjhipster-postgresql:
        extends:
            file: postgresql.yml
            service: pocjhipster-postgresql
